///init_monsters()
function init_monsters() {

	//Preallocate
	for(c = MONSTER_MAX; c >= 0; c--){
		for(d = MONSTER_DATA_MAX; d >= 0; d--){
			global.monster_data[c,d] = NONE;
		}
		global.monster_data[c,mond_NAME] = "Missing No."
	}

	//Make EXP groups as well
	//EXP groups are tuples of factors: [linear, quad]
	global.exp_group_factors[monexpgroup_FAST]		= [1.00, 1.00]
	global.exp_group_factors[monexpgroup_MID]		= [1.60, 1.12]
	global.exp_group_factors[monexpgroup_SLOW]		= [2.30, 1.24]
	global.exp_group_factors[monexpgroup_LEGENDARY] = [3.50, 1.55]

	//Create monsters explicitly
	///			id,							name,					sprite[battle,				map],						type1,				type2,			total-mhp-atk-def-mag-res-spd],	expgroup,				movelist[lv-move-...],																																														evolutionlist[[type-arg-mon,]...], (note the array of arrays!)   description (used as Monsterpedia text)
	init_monster(monster_DRACHNID,			"Drachnid",				[spr_mon_drachnid,			NONE],						type_FIRE,			NONE,			[200,	10, 5,11,20,15, 7],		monexpgroup_MID,		[[NONE,move_TACKLE],[NONE,move_UNNERVE],[NONE,move_FIREWEB],[15,move_FIREBALL],[25,move_MAGICTRANCE]],																										[[evotype_LEVEL,20,monster_CHARACHNE]],							"Chimaera with DNA from both spiders and dragons. Said to be man-made, but it's been known since long before biotechnology was invented. Might have been bred using alchemy, unless those rumors are just rumors.")
	init_monster(monster_CHARACHNE,			"Charachne",			[spr_mon_charachne,			NONE],						type_FIRE,			NONE,			[300,	10, 5,11,20,15, 7],		monexpgroup_MID,		[[NONE,move_TACKLE],[NONE,move_UNNERVE],[NONE,move_FIREWEB],[15,move_FIREBALL],[25,move_MAGICTRANCE]],																										[],																"Its half-humanoid form allows it great mobility, and its dragon blood grants it great magic power. Even in this young form, it strikes fear in the hearts of humans and monsters alike.")
	init_monster(monster_PLAUGSPOUT,		"Plaugspout",			[spr_mon_plaugsprout,		NONE],						type_PLANT,			NONE,			[200,	16,10,14, 8,15, 1],		monexpgroup_MID,		[[NONE,move_TACKLE],[NONE,move_POISONSPORE],[NONE,move_LEAFSHOT],[15,move_LEAFEXPLOSION],[25,move_MUSHROOMMISSILE]],																						[[evotype_LEVEL,20,monster_FLOWRATH]],							"Its sap is highly poisonous, owing to the amanita mushrooms growing naturally on its surface. This protects it from even the hardiest predators, but it still very paranoid and cautious.")
	init_monster(monster_FLOWRATH,			"Flowrath",				[spr_mon_flowrath,			NONE],						type_PLANT,			NONE,			[300,	16,10,14, 8,15, 1],		monexpgroup_MID,		[[NONE,move_TACKLE],[NONE,move_POISONSPORE],[NONE,move_LEAFSHOT],[15,move_LEAFEXPLOSION],[25,move_MUSHROOMMISSILE]],																						[],																"As it grows older and stronger, it becomes more aggressive, attacking first to chase predators and other threats away. It learns to take pleasure in causing pain and suffering.")
	init_monster(monster_DRAQUATIC,			"Draquatic",			[spr_mon_draquatic,			NONE],						type_WATER,			NONE,			[200,	10,11,10, 8,10,12],		monexpgroup_MID,		[[NONE,move_TACKLE],[NONE,move_DIVERGE],[NONE,move_BOOMBUBBLE],[15,move_WHIRLCUTTER],[25,move_BITE]],																										[[evotype_LEVEL,20,monster_LEVIOCEAN]],							"It lives deep underwater, hiding in the shadows to sneak up on prey. When brough up to the surface, it becomes disoriented in the sharp light, but many think its resulting clumsy behavior is cute.")
	init_monster(monster_LEVIOCEAN,			"Leviocean",			[spr_mon_leviocean,			NONE],						type_WATER,			NONE,			[300,	10,11,10, 8,10,12],		monexpgroup_MID,		[[NONE,move_TACKLE],[NONE,move_DIVERGE],[NONE,move_BOOMBUBBLE],[15,move_WHIRLCUTTER],[25,move_BITE]],																										[],																"It can spit out droplets of lumiscent acid to confuse and lure its prey. The light is so bright, jellyfish mistakes it for the moon from up to a mile away, and swim down instead of up.")
	init_monster(monster_GRODENT,			"Grodent",				[spr_mon_grodent,			NONE],						type_NORMAL,		NONE,			[120,	 7, 9,14, 3,14, 5],		monexpgroup_FAST,		[[NONE,move_TACKLE],[NONE,move_TAILWAG],[14,move_BLINDINGSAND],[19,move_BITE],[27,move_UNNERVE]],																											[[evotype_LEVEL,16,monster_RATSSIVE]],							"Hardy scavenger that is found all over the world, even being found on completely new continents. Its extremely filthy fur is a means of self-defense, as the mud dries into natural armor plates.")
	init_monster(monster_RATSSIVE,			"Ratssive",				[spr_mon_ratssive,			NONE],						type_NORMAL,		NONE,			[280,	 7, 9,14, 3,14, 5],		monexpgroup_MID,		[[NONE,move_TACKLE],[NONE,move_TAILWAG],[14,move_BLINDINGSAND],[19,move_BITE],[27,move_UNNERVE]],																											[],																"While it might look gigantic, it's not much larger than a Grodent. It creates an armored body using various discarded garbage and integrates it into its fur to look larger and more intimidating.")
	init_monster(monster_DUVAN,				"Duvan",				[spr_mon_duvan,				NONE],						type_AIR,			NONE,			[120,	 5,14, 7, 7, 5,14],		monexpgroup_FAST,		[[NONE,move_TACKLE],[NONE,move_BLINDINGSAND],[12,move_GUSTOFWIND],[16,move_UNNERVE]],																														[[evotype_LEVEL,21,monster_PIDGREAT]],							"Bird with a great sense of teamwork. A lone Duvan is disoriented and tends to fly into windows, but they often form flocks of hundreds of individuals to perform more significant tasks.")
	init_monster(monster_PIDGREAT,			"Pidgreat",				[spr_mon_pidgreat,			NONE],						type_AIR,			NONE,			[280,	 5,14, 7, 7, 5,14],		monexpgroup_MID,		[[NONE,move_TACKLE],[NONE,move_BLINDINGSAND],[12,move_GUSTOFWIND],[16,move_UNNERVE]],																														[],																"Majestic bird with impeccable loyalty and an impressive wingspan. In old days, they were trained to deliver letters and cargo, but the internet has made them obsolete.")
	init_monster(monster_JESTAR,			"Jestar",				[spr_mon_jestar,			NONE],						type_MAGIC,			NONE,			[150,	 4, 7, 7,14,12,10],		monexpgroup_FAST,		[[NONE,move_MAGICSTAR],[NONE,move_UNNERVE],[14,move_MAGICTRANCE],[20,move_BLINDINGSAND],[27,move_MAGICCARD]],																								[[evotype_LEVEL,22,monster_CARDEMON]],							"Mysterious creature with innate magic powers. They're normally very rare, but sightings increase hundredfold before a natural disaster is about to happen. It's seen as a bad omen as a result.")
	init_monster(monster_CARDEMON,			"Cardemon",				[spr_mon_cardemon,			NONE],						type_MAGIC,			NONE,			[330,	 4, 7, 7,14,12,10],		monexpgroup_MID,		[[NONE,move_MAGICSTAR],[NONE,move_UNNERVE],[14,move_MAGICTRANCE],[20,move_BLINDINGSAND],[27,move_MAGICCARD]],																								[],																"Dark magician that uses playing cards and dice to trap souls. Casino guards usually have these monsters to dissuade would-be cheaters.")
	init_monster(monster_MOLDOLE,			"Moldole",				[spr_mon_moldole,			NONE],						type_GROUND,		type_PLANT,		[165,	10,16,10, 6,11, 7],		monexpgroup_FAST,		[[NONE,move_MOLECLAW],[NONE,move_BLINDINGSAND],[12,move_LEAFSHOT],[18,move_POISONSPORE],[26,move_EARTHQUAKE]],																								[[evotype_LEVEL,26,monster_SHROOMOLE]],							"Mole that carries fungi on its back, planting saplings close to its lair for easy access to food. Also known as the green-thumb mole, and it's popular as a pet for gardeners.")
	init_monster(monster_SHROOMOLE,			"Shroomole",			[spr_mon_shroomole,			NONE],						type_GROUND,		type_PLANT,		[280,	10,16,10, 6,11, 7],		monexpgroup_MID,		[[NONE,move_MOLECLAW],[NONE,move_BLINDINGSAND],[12,move_LEAFSHOT],[18,move_POISONSPORE],[26,move_EARTHQUAKE]],																								[],																"Sometimes, a Moldole gets infected by the fungi it carries, and it is taken over and controlled by the mushrooms. Considering how sleepy and unaware they are, it's uncertain if they even notice.")
	init_monster(monster_SPOOKSHROOM,		"Spookshroom",			[spr_mon_spookshroom,		NONE],						type_PLANT,			type_GHOST,		[175,	14, 8,10,12,10,11],		monexpgroup_FAST,		[[NONE,move_ECTOPLASM],[NONE,move_POISONSPORE],[13,move_HAUNT],[22,move_MUSHROOMMISSILE],[30,move_MAGICTRANCE]],																							[[evotype_LEVEL,22,monster_WRAITHMANITA]],						"The ghost of a creature that died from a fungal infection. Driven by grudge, it tries to spread the infection among the living for revenge.")
	init_monster(monster_WRAITHMANITA,		"Wraithmanita",			[spr_mon_wraithmanita,		NONE],						type_PLANT,			type_GHOST,		[310,	14, 8,10,12,10,11],		monexpgroup_MID,		[[NONE,move_ECTOPLASM],[NONE,move_POISONSPORE],[13,move_HAUNT],[22,move_MUSHROOMMISSILE],[30,move_MAGICTRANCE]],																							[],																"As its anger intensifies, the ghost becomes better at manifesting physically. As a result, the half-ethereal mushroom grows larger, furthering the infection and causing more anger and grudges.")


}
